# Generated by Django 6.0.7 on 2026-08-06 15:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('fapshi', 'Fapshi'), ('stripe', 'Stripe'), ('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money')], max_length=20)),
                ('direction', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='initiated', max_length=20)),
                ('appointment_id', models.UUIDField(blank=True, db_index=True, help_text='Linked appointment UUID if applicable.', null=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('internal_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('provider_transaction_id', models.CharField(blank=True, default='', max_length=255)),
                ('checkout_url', models.URLField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('cash_in', 'Cash In'), ('cash_out', 'Cash Out'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('escrow_refund', 'Escrow Refund'), ('platform_fee', 'Platform Fee'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = credit, negative = debit.', max_digits=15)),
                ('appointment_id', models.UUIDField(blank=True, db_index=True, help_text='Linked appointment UUID if applicable.', null=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.payment')),
            ],
            options={
                'verbose_name': 'ledgerentry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(default='fapshi', help_text='Gateway name: fapshi, tangentopay, etc.', max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('raw_payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_logs', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'payment gateway log',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('escrow_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.wallet'),
        ),
        migrations.AddField(
            model_name='payment',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.wallet'),
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_id', models.UUIDField(db_index=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform commission deducted on release.', max_digits=15)),
                ('status', models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], db_index=True, default='held', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hold_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_hold', to='payments.transaction')),
                ('release_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_release', to='payments.transaction')),
                ('provider_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrows_as_provider', to='payments.wallet')),
                ('seeker_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrows_as_seeker', to='payments.wallet')),
            ],
            options={
                'verbose_name': 'escrow account',
            },
        ),
        migrations.CreateModel(
            name='WalletPin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin_hash', models.CharField(max_length=128)),
                ('salt', models.CharField(max_length=64)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_pin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet PIN',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], max_length=15)),
                ('recipient_reference', models.CharField(help_text='Mobile money number (E.164) or bank account number.', max_length=100)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], db_index=True, default='pending', max_length=10)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='payments.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='payments.wallet')),
            ],
            options={
                'verbose_name': 'withdrawal request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='payments_wa_user_id_cd1a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'transaction_type'], name='payments_tr_wallet__f5c525_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['appointment_id'], name='payments_tr_appoint_75275b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider'], name='payments_pa_provide_502c98_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['internal_reference'], name='payments_pa_interna_d7c5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_reference'], name='payments_pa_provide_48cfd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='payment_user_idempotency_unique'),
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['status'], name='payments_es_status_b64aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', 'created_at'], name='payments_wi_status_90f0fd_idx'),
        ),
    ]
