# Generated by Django 6.0.7 on 2026-08-07 18:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='withdrawalrequest',
            name='payments_wi_status_90f0fd_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('mtn_mobile_money', 'Mobile Money'), ('orange_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='reserved_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Funds reserved for pending operations such as cash-outs.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('fapshi', 'Fapshi'), ('stripe', 'Stripe')], max_length=20),
        ),
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
