# Generated by Django 6.0.7 on 2026-08-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_withdrawalrequest_payments_wi_status_90f0fd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('mobile money', 'Mobile Money'), ('orange money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], max_length=50, null=True),
        ),
    ]
