# Generated by Django 6.0.7 on 2026-08-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_phone_number_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, choices=[('mtn_mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('bank_transfer', 'Bank Transfer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
