# Generated by Django 6.0.7 on 2026-09-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.CharField(choices=[('available', 'Available Balance'), ('escrow', 'Escrow Balance'), ('clearing', 'External Clearing')], db_index=True, default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['idempotency_key'], name='payments_tr_idempot_801f50_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment_id', None), _negated=True), fields=('appointment_id', 'transaction_type', 'account'), name='transaction_appointment_leg_unique'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('payment', None), _negated=True), fields=('payment', 'transaction_type', 'account'), name='transaction_payment_leg_unique'),
        ),
    ]
