# Generated by Django 6.0.7 on 2026-09-07 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_account_transaction_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('cash_in', 'Wallet Top-up'), ('cash_out', 'Withdrawal'), ('escrow_held', 'Payment Held for Appointment'), ('escrow_released', 'Payment Sent'), ('escrow_refunded', 'Refund'), ('earning', 'Earning Received')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='completed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('appointment_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('related_transactions', models.ManyToManyField(related_name='activity_entries', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_activity', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='payments.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='payments_wa_user_id_757407_idx')],
            },
        ),
    ]
