# Generated by Django 6.0.7 on 2026-09-21 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_walletactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewaylog',
            name='provider_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='walletactivity',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_activities', to='payments.payment'),
        ),
        migrations.AddConstraint(
            model_name='paymentgatewaylog',
            constraint=models.UniqueConstraint(fields=('gateway', 'provider_transaction_id'), name='gateway_log_unique'),
        ),
    ]
