# Generated by Django 6.0.7 on 2026-08-13 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_alter_appointment_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seeker_statement', models.TextField()),
                ('provider_statement', models.TextField()),
                ('provider_statement_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('resolution', models.CharField(blank=True, choices=[('refund_seeker', 'Full Refund to Seeker'), ('release_provider', 'Release to Provider'), ('split', 'Split Between Parties')], max_length=20, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('split_percent_seeker', models.PositiveBigIntegerField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved_seeker', 'Resolved - Seeker'), ('resolved_provider', 'Resolved - Provider'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='appointments.appointment')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'is_Staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dispute',
                'verbose_name_plural': 'disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispute_id_snapshot', models.UUIDField()),
                ('action', models.CharField(choices=[('raised', 'Dispute Raised'), ('statement_seeker', 'Seeker Statement Added'), ('evidence_uploaded', 'Evidence Uploaded'), ('under_review', 'Marked Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20)),
                ('actor_role', models.CharField(blank=True, default='', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('diff', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='disputes.dispute')),
            ],
            options={
                'verbose_name': 'dispute audit log',
                'verbose_name_plural': 'dispute audit logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='disputes.dispute')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dispute evidence',
                'verbose_name_plural': 'dispute evidence',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'created_at'], name='disputes_di_status_edf3a9_idx'),
        ),
    ]
