# Generated by Django 6.0.7 on 2026-08-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispute',
            old_name='resolution_note',
            new_name='resolution_notes',
        ),
    ]
