# Generated by Django 6.0.7 on 2026-08-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_rename_resolution_note_dispute_resolution_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputeauditlog',
            name='action',
            field=models.CharField(choices=[('raised', 'Dispute Raised'), ('statement_seeker', 'Seeker Statement Added'), ('statement_provider', 'Provider Statement Added'), ('evidence_uploaded', 'Evidence Uploaded'), ('under_review', 'Marked Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20),
        ),
    ]
