# Generated by Django 6.0.7 on 2026-07-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=24, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=24, max_digits=24, null=True),
        ),
    ]
