# Generated by Django 6.0.7 on 2026-07-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_providerprofile_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=24, null=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=24, null=True),
        ),
    ]
