# Generated by Django 6.0.7 on 2026-07-15 12:43

import accounts.models.portfolio
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_providerprofile_location_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', max_length=2000, verbose_name='description')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='category')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='completed on')),
                ('client_name', models.CharField(blank=True, default='', help_text='Optional — only shown if provider chooses to display it.', max_length=200, verbose_name='client name')),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=1000, validators=[django.core.validators.URLValidator(), accounts.models.portfolio.validate_media_url_extension], verbose_name='cover image URL')),
                ('cover_image_public_id', models.CharField(blank=True, default='', help_text='Cloudinary public_id or S3 object key, used for deletion via SDK.', max_length=500, verbose_name='cover image storage key')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='accounts.providerprofile')),
            ],
            options={
                'verbose_name': 'portfolio item',
                'verbose_name_plural': 'portfolio items',
                'ordering': ['display_order', '-completed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator(), accounts.models.portfolio.validate_media_url_extension], verbose_name='media URL')),
                ('public_id', models.CharField(blank=True, default='', help_text='Cloudinary public_id or S3 object key, used for deletion via SDK.', max_length=500, verbose_name='storage key')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('thumbnail_url', models.URLField(blank=True, default='', help_text='Optional — e.g. video poster frame or resized preview.', max_length=1000, verbose_name='thumbnail URL')),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='caption')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.portfolioitem')),
            ],
            options={
                'verbose_name': 'portfolio image',
                'verbose_name_plural': 'portfolio images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['provider', 'is_published'], name='accounts_po_provide_33cf39_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_featured'], name='accounts_po_is_feat_0d11d0_idx'),
        ),
    ]
