# Generated by Django 6.0.7 on 2026-07-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_portfolioitem_portfolioimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycdocument',
            old_name='file',
            new_name='file_url',
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last password change. Used to invalidate tokens issued before this time.', null=True),
        ),
    ]
