# Generated by Django 6.0.7 on 2026-07-13 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Human-readable name, e.g. 'Plumbing'.", max_length=100, verbose_name='title')),
                ('slug', models.SlugField(help_text='URL-safe identifier, auto-generated from title.', max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', help_text='Optional category description shown to users.', verbose_name='description')),
                ('icon_url', models.URLField(blank=True, default='', help_text='S3 URL for category icon used in the mobile app.', verbose_name='icon URL')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive categories are hidden from public endpoints.', verbose_name='active')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower values appear first. 0 = default ordering by title.', verbose_name='display order')),
                ('provider_count', models.PositiveIntegerField(default=0, help_text='Cached count of verified providers offering this category.', verbose_name='provider count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent for sub-categories.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_slug', models.SlugField(help_text='Preserved even if the category is later deleted.', max_length=120)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('activated', 'Activated'), ('deactivated', 'Deactivated')], max_length=15)),
                ('diff', models.JSONField(default=dict, help_text='Fields changed: {field: [old_value, new_value]}.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='categories.category')),
            ],
            options={
                'verbose_name': 'category audit log',
                'verbose_name_plural': 'category audit logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_categories', to='categories.category')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_categories', to='accounts.providerprofile')),
            ],
            options={
                'verbose_name': 'provider category',
                'verbose_name_plural': 'provider categories',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'parent'], name='categories__is_acti_51b5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='categories__slug_9b1a28_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providercategory',
            unique_together={('provider', 'category')},
        ),
    ]
