# Generated by Django 6.0.7 on 2026-08-21 17:29

import django.db.models.deletion
import reviews._help
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0003_alter_appointment_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communication_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[reviews._help._validate_half_step])),
                ('punctuality_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[reviews._help._validate_half_step])),
                ('quality_rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[reviews._help._validate_half_step])),
                ('overall_rating', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('comment', models.TextField(blank=True, default='', max_length=1000)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('flag_reason', models.TextField(blank=True, default='')),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('provider_response', models.TextField(blank=True, default='', max_length=500)),
                ('provider_response_at', models.DateTimeField(blank=True, null=True)),
                ('edit_locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='appointments.appointment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_received', to='accounts.providerprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'is_visible', '-created_at'], name='reviews_rev_provide_ac52a6_idx'), models.Index(fields=['reviewer'], name='reviews_rev_reviewe_e817a5_idx'), models.Index(fields=['is_flagged'], name='reviews_rev_is_flag_790b01_idx')],
            },
        ),
    ]
