# Generated by Django 6.0.7 on 2026-08-22 08:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0003_alter_appointment_customer'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='appointments.appointment'),
        ),
        migrations.CreateModel(
            name='ProviderReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('avg_communication', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('avg_punctuality', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('avg_quality', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('avg_overall', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('star_distribution', models.JSONField(default=dict)),
                ('last_upated', models.DateTimeField(auto_now=True)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_summary', to='accounts.providerprofile')),
            ],
            options={
                'verbose_name': 'provider review summary',
                'verbose_name_plural': 'provider review summaries',
            },
        ),
        migrations.CreateModel(
            name='ReviewAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_id_snapshot', models.UUIDField()),
                ('action', models.CharField(choices=[('flagged', 'Flagged'), ('unflagged', 'Unflagged'), ('removed', 'Removed'), ('restored', 'Restored'), ('response_removed', 'Response Removed')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('diff', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='reviews.review')),
            ],
            options={
                'verbose_name': 'review audit log',
                'verbose_name_plural': 'review audit logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
