# Generated by Django 6.0.7 on 2026-08-06 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_address', models.TextField(help_text='Human-readable service address.')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of service location (PostGIS Point in production).', max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField()),
                ('notes', models.TextField(blank=True, default='', help_text='Special instructions from the seeker.')),
                ('quoted_price', models.DecimalField(decimal_places=2, help_text='Price agreed at booking time. Moved into escrow on creation.', max_digits=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Actual final price. May differ from quoted_price.', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('auto_released', 'Auto-Released'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=15)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('completion_proof', models.URLField(blank=True, default='', help_text='S3 URL of provider-uploaded completion photo/video.')),
                ('completion_notes', models.TextField(blank=True, default='')),
                ('escrow_transaction_id', models.UUIDField(blank=True, help_text='ID of the escrow Transaction created by the payments module.', null=True)),
                ('reminder_sent_24h', models.BooleanField(default=False)),
                ('reminder_sent_2h', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='categories.category')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_as_customer', to='accounts.seekerprofile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_as_provider', to='accounts.providerprofile')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=15)),
                ('to_status', models.CharField(max_length=15)),
                ('actor_id', models.CharField(blank=True, default=None, help_text='UUID of the User who triggered the transition.', max_length=36, null=True)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'appointment status log',
                'verbose_name_plural': 'appointment status logs',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blocked_date', models.DateField(db_index=True)),
                ('blocked_start', models.TimeField()),
                ('blocked_end', models.TimeField()),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='accounts.providerprofile')),
            ],
            options={
                'verbose_name': 'provider availability block',
                'verbose_name_plural': 'provider availability blocks',
                'ordering': ['blocked_date', 'blocked_start'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_date'], name='appointment_status_93b56b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['provider', 'status'], name='appointment_provide_afe878_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', 'status'], name='appointment_custome_6b9467_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'completed_at'], name='appointment_status_e1e135_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'created_at'], name='appointment_status_cceeb8_idx'),
        ),
    ]
