# Generated by Django 6.0.7 on 2026-08-08 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_status_93b56b_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'scheduled_at'], name='appointment_status_eec9f6_idx'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='scheduled_time',
        ),
    ]
