# Generated by Django 6.0.7 on 2026-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending_pin', 'pending_pin'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('auto_released', 'Auto-Released'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending_pin', max_length=15),
        ),
    ]
