# Generated by Django 6.0.7 on 2026-09-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('confirmed', 'Confirmed'), ('auto_released', 'Auto-Released'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='initiated', max_length=15),
        ),
    ]
