# Generated by Django 6.0.7 on 2026-07-21 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('template', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Spam Complaint'), ('failed', 'Failed')], default='sent', max_length=15)),
                ('event_id', models.CharField(blank=True, max_length=64)),
                ('ses_message_id', models.CharField(blank=True, max_length=200)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email log',
                'verbose_name_plural': 'email logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('account_verified', 'Account Verified'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('booking_request', 'New Booking Request'), ('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('job_started', 'Job Started'), ('job_completed', 'Job Completed'), ('job_confirmed', 'Job Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_expired', 'Booking Expired'), ('escrow_auto_released', 'Escrow Auto-Released'), ('reminder_24h', 'Appointment Reminder 24h'), ('reminder_2h', 'Appointment Reminder 2h'), ('wallet_credited', 'Wallet Credited'), ('withdrawal_initiated', 'Withdrawal Initiated'), ('withdrawal_completed', 'Withdrawal Completed'), ('withdrawal_failed', 'Withdrawal Failed'), ('review_received', 'Review Received'), ('review_reminder', 'Review Reminder'), ('review_flagged', 'Review Flagged'), ('review_removed', 'Review Removed'), ('review_response', 'Provider Replied to Review'), ('dispute_raised', 'Dispute Raised'), ('dispute_resolved', 'Dispute Resolved'), ('system', 'System')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict, help_text='Structured JSON payload for deep-linking in the Flutter app.')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('account_verified', 'Account Verified'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('booking_request', 'New Booking Request'), ('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('job_started', 'Job Started'), ('job_completed', 'Job Completed'), ('job_confirmed', 'Job Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_expired', 'Booking Expired'), ('escrow_auto_released', 'Escrow Auto-Released'), ('reminder_24h', 'Appointment Reminder 24h'), ('reminder_2h', 'Appointment Reminder 2h'), ('wallet_credited', 'Wallet Credited'), ('withdrawal_initiated', 'Withdrawal Initiated'), ('withdrawal_completed', 'Withdrawal Completed'), ('withdrawal_failed', 'Withdrawal Failed'), ('review_received', 'Review Received'), ('review_reminder', 'Review Reminder'), ('review_flagged', 'Review Flagged'), ('review_removed', 'Review Removed'), ('review_response', 'Provider Replied to Review'), ('dispute_raised', 'Dispute Raised'), ('dispute_resolved', 'Dispute Resolved'), ('system', 'System')], max_length=40)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
